categories:
  - title: '🚀 General features'
    labels:
      - 'enhancement'
  - title: '🔭 Pipeline applications'
    labels:
      - 'pipeline applications'
  - title: '🌐 GRID support'
    labels:
      - 'grid'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'wrong behaviour'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'documentation'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |

  ## Summary
  
  ...
  
  ## Contributors
  
  $CONTRIBUTORS

  ## What is changed since $PREVIOUS_TAG
  
  Pull-requests containing changes of multiple nature are repeated.
  
  $CHANGES
