name: protopipe-dev
channels:
  - defaults
dependencies:
  - python >=3.7,<3.9
  - pip
  - conda-forge::ctapipe=0.11.0
  - conda-forge::gammapy
  - astropy>=4.0.1
  - h5py=2
  - ipython
  - jupyterlab
  - conda-forge::nbsphinx
  - notebook
  - numpydoc
  - pandas
  - pytest
  - conda-forge::sphinx-automodapi
  - sphinx_rtd_theme
  - conda-forge::sphinx-issues
  - conda-forge::uproot
  - conda-forge::vitables
  - pip:
    - papermill
    - pyirf
    - pytest-dependency
