General:
 model_type: 'regressor'
 # [...] = your analysis local path
 # Please, refer to directory structure shown at Lugano
 data_dir: '[...]/data/DL1/for_energy_estimation'
 data_file: 'dl1_{}_gamma_merged.h5'
 outdir: '[...]/estimators/energy_regressor'
 cam_id_list: ['LSTCam', 'NectarCam']
 table_name_template: ''

Split:
 train_fraction: 0.8

Method:
 name: 'AdaBoostRegressor'
 target_name: 'true_energy'
 tuned_parameters:
  learning_rate: [0.3]
  n_estimators: [100]
  base_estimator__max_depth: [null]  # null is equivalent to None
  base_estimator__min_samples_split: [2]
  base_estimator__min_samples_leaf: [10]
 scoring: 'explained_variance'
 cv: 2

FeatureList:
 - 'log10_hillas_intensity'
 - 'log10_impact_dist'
 - 'hillas_width_reco'
 - 'hillas_length_reco'
 - 'h_max'

SigFiducialCuts:
 - 'good_image == 1'  # image survived the quality cuts
 - 'is_valid == True' # shower correctly reconstructed

Diagnostic:
 # Energy binning in TeV (used for reco and true energy)
 energy:
  nbins: 21
  min: 0.0125
  max: 200.0
